spring:
  application:
    name: consertreservation
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:./data;NON_KEYWORDS=USER
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379